
```{r}
# Libraries

required_packages <- c("DESeq2", "readr", "magrittr", "ggplot2", "dplyr", "ConsensusClusterPlus", "cluster", "factoextra", "pheatmap", "ggalluvial", "mclust", "randomForest")

for (package in required_packages) {
  if (!requireNamespace(package, quietly = TRUE)) {
    if (package %in% c("ConsensusClusterPlus", "factoextra")) {
      if (!requireNamespace("BiocManager", quietly = TRUE)) {
        install.packages("BiocManager")
      }
      BiocManager::install(package)
    } else {
      install.packages(package)
    }
  }
}

library(DESeq2)
library(readr)
library(magrittr)
library(ggplot2)
library(dplyr)
library(factoextra)
library(randomForest)
library(pheatmap)


```


```{r}
# Log-scale the data and use HUGO symbols

metadata_file <- "data/SRP125001/metadata_SRP125001.tsv"
data_file <- "data/SRP125001/SRP125001.tsv"

# Read in metadata TSV file
metadata <- readr::read_tsv(metadata_file)

# Read in data TSV file
expression_df <- readr::read_tsv(data_file) %>%
  # Tuck away the Gene ID column as row names
  tibble::column_to_rownames("Gene")

# Make the data in the order of the metadata
expression_df <- expression_df %>%
  dplyr::select(metadata$refinebio_accession_code)

# Check if this is in the same order
all.equal(colnames(expression_df), metadata$refinebio_accession_code)

# Log scale the data frame
expression_df_log <- expression_df %>%
  # Apply log transformation to all columns except the "Gene" column
  mutate(across(everything(), ~log(., base = 2)))

```


```{r}
# 5000 most variable genes.

mads=apply(expression_df_log,1,mad)
top_5000_genes_mads=expression_df_log[rev(order(mads))[1:5000],]

# other numbers of most variable genes
top_10_genes=expression_df_log[rev(order(mads))[1:10],]
top_100_genes=expression_df_log[rev(order(mads))[1:100],]
top_1000_genes=expression_df_log[rev(order(mads))[1:1000],]
top_10000_genes=expression_df_log[rev(order(mads))[1:10000],]

```


```{r}
# transposes the data and adds the appropriate label to each sample
# the names for 10-10000 genes are transposed_df_10, transposed_df_100, transposed_df_1000, transposed_df_10000

# transposes the data
transposed_df <- t(top_5000_genes_mads)
transposed_df <- as.data.frame(transposed_df)

# adds a new column containing the labels (lung tumor, tumor adjacent, control).
transposed_df$Labels <- metadata$refinebio_title[match(rownames(transposed_df), metadata$refinebio_accession_code)]

# makes the labels the same
transposed_df$Labels <- ifelse(grepl("^Control", transposed_df$Labels), "Control",
                        ifelse(grepl("^Lung_tumor_", transposed_df$Labels), "Tumor Adjacent",
                        ifelse(grepl("^Lung_tumor ", transposed_df$Labels), "Tumor", transposed_df$Labels)))

# turns Labels column into categorical data
transposed_df$Labels = factor(transposed_df$Labels) 

```


```{r}
# Random Forest

# Trains the randomForest on data excluding 15 samples, tests on the remaining 15
training_df <- transposed_df[1:(nrow(transposed_df) - 15), ]
testing_df <- tail(transposed_df, 15)

# creates randomForest object
rf <- randomForest(Labels ~ ., data = training_df, ntree = 2001, importance = TRUE)
rf

```

```{r}
# Saves the error tree of the random forest

png("Plots/assignment4/randomForest_plot_5000genes.png")
plot(rf, main="Random Forest OOB Error Plot")
dev.off()
plot(rf, main="Random Forest OOB Error Plot")


```


```{r}
# tests on the predictive model

result <- data.frame(testing_df$Labels, predict(rf, testing_df, type="response"))

png("Plots/assignment4/randomForestTestingPlot.png")
plot(result, main="Random Forest Prediction with 5000 Genes", ylab="Probability", xlab="Categories")
dev.off()
plot(result, main="Random Forest Prediction with 5000 Genes", ylab="Probability", xlab="Categories")

```


```{r}
# extracts the top 10% (500 genes) most impactful genes in the predictive model

importance_data <- rf$importance
importance_data <- as.data.frame(importance_data)
sorted_genes_by_importance <- importance_data[order(importance_data$MeanDecreaseAccuracy, decreasing = TRUE), ]
n_rows <- nrow(sorted_genes_by_importance)
top_10_percent <- round(0.10 * n_rows)
top_10_percent_genes_randomForest <- sorted_genes_by_importance[1:top_10_percent, ]

top_10_percent_genes_randomForest

```

```{r}
# Creates transpose df of 10 to 10000 genes, with labels
# names are transposed_df_10, transposed_df_100, transposed_df_1000, transposed_df_10000

transposed_df_10 <- t(top_10_genes)
transposed_df_10 <- as.data.frame(transposed_df_10)
transposed_df_10$Labels <- metadata$refinebio_title[match(rownames(transposed_df_10), metadata$refinebio_accession_code)]
transposed_df_10$Labels <- ifelse(grepl("^Control", transposed_df_10$Labels), "Control",
                ifelse(grepl("^Lung_tumor_", transposed_df_10$Labels), "Tumor Adjacent",
                ifelse(grepl("^Lung_tumor ", transposed_df_10$Labels), "Tumor", transposed_df_10$Labels)))
transposed_df_10$Labels = factor(transposed_df_10$Labels) 

transposed_df_100 <- t(top_100_genes)
transposed_df_100 <- as.data.frame(transposed_df_100)
transposed_df_100$Labels <- metadata$refinebio_title[match(rownames(transposed_df_100), metadata$refinebio_accession_code)]
transposed_df_100$Labels <- ifelse(grepl("^Control", transposed_df_100$Labels), "Control",
                ifelse(grepl("^Lung_tumor_", transposed_df_100$Labels), "Tumor Adjacent",
                ifelse(grepl("^Lung_tumor ", transposed_df_100$Labels), "Tumor", transposed_df_100$Labels)))
transposed_df_100$Labels = factor(transposed_df_100$Labels) 

transposed_df_1000 <- t(top_1000_genes)
transposed_df_1000 <- as.data.frame(transposed_df_1000)
transposed_df_1000$Labels <- metadata$refinebio_title[match(rownames(transposed_df_1000), metadata$refinebio_accession_code)]
transposed_df_1000$Labels <- ifelse(grepl("^Control", transposed_df_1000$Labels), "Control",
                ifelse(grepl("^Lung_tumor_", transposed_df_1000$Labels), "Tumor Adjacent",
                ifelse(grepl("^Lung_tumor ", transposed_df_1000$Labels), "Tumor", transposed_df_1000$Labels)))
transposed_df_1000$Labels = factor(transposed_df_1000$Labels) 

transposed_df_10000 <- t(top_10000_genes)
transposed_df_10000 <- as.data.frame(transposed_df_10000)
transposed_df_10000$Labels <- metadata$refinebio_title[match(rownames(transposed_df_10000), metadata$refinebio_accession_code)]
transposed_df_10000$Labels <- ifelse(grepl("^Control", transposed_df_10000$Labels), "Control",
                ifelse(grepl("^Lung_tumor_", transposed_df_10000$Labels), "Tumor Adjacent",
                ifelse(grepl("^Lung_tumor ", transposed_df_10000$Labels), "Tumor", transposed_df_10000$Labels)))
transposed_df_10000$Labels = factor(transposed_df_10000$Labels) 

```


```{r}
# randomForest on 10 genes

# creates randomForest object
training_df <- transposed_df_10[1:(nrow(transposed_df_10) - 15), ]
testing_df <- tail(transposed_df_10, 15)
rf <- randomForest(Labels ~ ., data = training_df, ntree = 2001, importance = TRUE)
rf

# predicts, then saves the outcome
result <- data.frame(testing_df$Labels, predict(rf, testing_df, type="response"))
png("Plots/assignment4/randomForestTestingPlot_10genes.png")
plot(result, main="Random Forest Prediction with 10 Genes", ylab="Probability", xlab="Categories")
dev.off()
plot(result, main="Random Forest Prediction with 10 Genes", ylab="Probability", xlab="Categories")

# top 10% most impactful genes
importance_data <- rf$importance
importance_data <- as.data.frame(importance_data)
sorted_genes_by_importance <- importance_data[order(importance_data$MeanDecreaseAccuracy, decreasing = TRUE), ]
n_rows <- nrow(sorted_genes_by_importance)
top_10_percent <- round(0.10 * n_rows)
randomForest_10genes_impactful <- sorted_genes_by_importance[1:top_10_percent, ]
randomForest_10genes_impactful

```



```{r}
# randomForest on 100 genes

# creates randomForest object
training_df <- transposed_df_100[1:(nrow(transposed_df_100) - 15), ]
testing_df <- tail(transposed_df_100, 15)
rf <- randomForest(Labels ~ ., data = training_df, ntree = 2001, importance = TRUE)
rf

# predicts, then saves the outcome
result <- data.frame(testing_df$Labels, predict(rf, testing_df, type="response"))
png("Plots/assignment4/randomForestTestingPlot_100genes.png")
plot(result, main="Random Forest Prediction with 100 Genes", ylab="Probability", xlab="Categories")
dev.off()
plot(result, main="Random Forest Prediction with 100 Genes", ylab="Probability", xlab="Categories")

# top 10% most impactful genes
importance_data <- rf$importance
importance_data <- as.data.frame(importance_data)
sorted_genes_by_importance <- importance_data[order(importance_data$MeanDecreaseAccuracy, decreasing = TRUE), ]
n_rows <- nrow(sorted_genes_by_importance)
top_10_percent <- round(0.10 * n_rows)
randomForest_100genes_impactful <- sorted_genes_by_importance[1:top_10_percent, ]
randomForest_100genes_impactful

```

```{r}
# randomForest on 1000 genes

# creates randomForest object
training_df <- transposed_df_1000[1:(nrow(transposed_df_1000) - 15), ]
testing_df <- tail(transposed_df_1000, 15)
rf <- randomForest(Labels ~ ., data = training_df, ntree = 2001, importance = TRUE)
rf

# predicts, then saves the outcome
result <- data.frame(testing_df$Labels, predict(rf, testing_df, type="response"))
png("Plots/assignment4/randomForestTestingPlot_1000genes.png")
plot(result, main="Random Forest Prediction with 1000 Genes", ylab="Probability", xlab="Categories")
dev.off()
plot(result, main="Random Forest Prediction with 1000 Genes", ylab="Probability", xlab="Categories")

# top 10% most impactful genes
importance_data <- rf$importance
importance_data <- as.data.frame(importance_data)
sorted_genes_by_importance <- importance_data[order(importance_data$MeanDecreaseAccuracy, decreasing = TRUE), ]
n_rows <- nrow(sorted_genes_by_importance)
top_10_percent <- round(0.10 * n_rows)
randomForest_1000genes_impactful <- sorted_genes_by_importance[1:top_10_percent, ]
randomForest_1000genes_impactful

```

```{r}
# randomForest on 10000 genes

# creates randomForest object
training_df <- transposed_df_10000[1:(nrow(transposed_df_10000) - 15), ]
testing_df <- tail(transposed_df_10000, 15)
rf <- randomForest(Labels ~ ., data = training_df, ntree = 2001, importance = TRUE)
rf

# predicts, then saves the outcome
result <- data.frame(testing_df$Labels, predict(rf, testing_df, type="response"))
png("Plots/assignment4/randomForestTestingPlot_10000genes.png")
plot(result, main="Random Forest Prediction with 10000 Genes", ylab="Probability", xlab="Categories")
dev.off()
plot(result, main="Random Forest Prediction with 10000 Genes", ylab="Probability", xlab="Categories")

# top 10% most impactful genes
importance_data <- rf$importance
importance_data <- as.data.frame(importance_data)
sorted_genes_by_importance <- importance_data[order(importance_data$MeanDecreaseAccuracy, decreasing = TRUE), ]
n_rows <- nrow(sorted_genes_by_importance)
top_10_percent <- round(0.10 * n_rows)
randomForest_10000genes_impactful <- sorted_genes_by_importance[1:top_10_percent, ]
randomForest_10000genes_impactful

```


```{r}
# Random Forest
# What percent of impactful genes are in the impactful genes of the 10000 sample?

# Get the row names from all three data sets
row_names_10genes <- rownames(randomForest_10genes_impactful)
row_names_100genes <- rownames(randomForest_100genes_impactful)
row_names_1000genes <- rownames(randomForest_100genes_impactful)
row_names_5000genes <- rownames(top_10_percent_genes_randomForest)
row_names_10000genes <- rownames(randomForest_10000genes_impactful)

# Calculate the percentages for both 10 genes and 100 genes
percentage_10genes <- (length(intersect(row_names_10genes, row_names_10000genes)) / 
                         length(row_names_10genes)) * 100
percentage_100genes <- (length(intersect(row_names_100genes, row_names_10000genes)) / 
                          length(row_names_100genes)) * 100
percentage_1000genes <- (length(intersect(row_names_1000genes, row_names_10000genes)) /
                           length(row_names_1000genes)) * 100
percentage_5000genes <- (length(intersect(row_names_5000genes, row_names_10000genes)) /
                           length(row_names_5000genes)) * 100


# Create a data frame to store the percentages
percentages_df <- data.frame(
  Dataset = c("10 Genes", "100 Genes", "1000 Genes", "5000 Genes"),
  Percentage = c(percentage_10genes, percentage_100genes, percentage_1000genes, percentage_5000genes)
)

png("Plots/assignment4/randomForest_overlap_chart.png")

# Create a histogram
barplot(percentages_df$Percentage, 
        names.arg = percentages_df$Dataset, 
        col = "lightblue", 
        main = "Impact Genes Overlap Compared to 10000 Sample", 
        xlab = "Sample Name",
        ylab = "Overlap Percentage")

dev.off()

barplot(percentages_df$Percentage, 
        names.arg = percentages_df$Dataset, 
        col = "lightblue", 
        main = "Impact Genes Overlap Compared to 10000 Sample", 
        xlab = "Sample Name",
        ylab = "Overlap Percentage")


```

```{r}
# filters the impactful genes from the data set
common_row_names <- intersect(rownames(randomForest_10000genes_impactful), rownames(expression_df))
filtered_expression_df <- expression_df[common_row_names, ]

# reads in meta data with rowname already set
metadata_withRowNames <- readr::read_tsv(metadata_file) %>%
  tibble::column_to_rownames("refinebio_accession_code")

# creates the annotation data frame
annotation <- metadata_withRowNames[c("refinebio_title")]
annotation$refinebio_title <- ifelse(grepl("^Control", annotation$refinebio_title), "Control",
              ifelse(grepl("^Lung_tumor_", annotation$refinebio_title), "TumorAdjacent",
              ifelse(grepl("^Lung_tumor ", annotation$refinebio_title), "Tumor", annotation$refinebio_title)))
names(annotation)[names(annotation) == "refinebio_title"] <- "SampleGroup"

```


```{r}
# Heat map of randomForest with the 10000 genes sample

png("Plots/assignment4/heatmap_randomForest_10000genes.png")

# Create the heatmap
heatmap <- pheatmap(
  filtered_expression_df,
  annotation_col = annotation,
  show_rownames = FALSE,
  cluster_cols = TRUE,
  cluster_rows = TRUE,
  scale = "none",
  main = "Random Forest Impactful Genes",
)

print(heatmap)
dev.off()

```











































